bitrise.yml updated

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -29,10 +29,6 @@ workflows:
     - deploy-to-bitrise-io@1: {}
     - cache-push@2: {}
   primary:
-    envs:
-    - BITRISE_INFOPLIST_PATH: SwiftNewsCrawler/SwiftNewsCrawler/whiteInfo.plist
-    - BITRISE_APPETIZE_TOKEN: tok_kaq602vwkwuv14ajrcrd0zfra8
-    - BITRISE_APP_NAME: THIS_IS_TSET
     steps:
     - activate-ssh-key@4:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
@@ -91,11 +87,7 @@ workflows:
             echo $productName
 
             appName=$(/usr/libexec/PlistBuddy -c "Print CFBundleName"
-            "${BITRISE_INFOPLIST_PATH}")
-            echo $appName
-    - xcode-archive@2:
-        inputs:
-        - export_method: development
+            "${BITRISE_INFOPLIST_PATH}") echo $appName
     - certificate-and-profile-installer@1: {}
     - xcode-test@2:
         inputs:
@@ -105,18 +97,109 @@ workflows:
     - deploy-to-bitrise-io@1: {}
     - cache-push@2: {}
   PrimarySimulator:
-    envs:
-    - BITRISE_INFOPLIST_PATH: SwiftNewsCrawler/SwiftNewsCrawler/whiteInfo.plist
-    - BITRISE_APP_NAME: THIS_IS_TSET
-    - BITRISE_APP_DIR_ZIP_PATH: SwiftNewsCrawler/SwiftNewsCrawler
     steps:
     - activate-ssh-key@4:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
     - git-clone@4: {}
     - cache-pull@2: {}
+    - set-ios-info-plist-unified@1:
+        inputs:
+        - bundle_identifier: com.pri.swiftnewscrawler
+        - bundle_version: 1.0.3
+        - bundle_version_short: '23'
+        - bundle_name: WhiteLabelNews
+        - bundle_display_name: ''
+        - app_icon_asset_catalog: SwiftNewsCrawler/WhiteLabelTest/Assets.xcassets/AppIcon.appiconset
+        - info_plist_file: $BITRISE_INFOPLIST_PATH
     - xcode-project-info@2:
         inputs:
         - info_plist_path: $BITRISE_INFOPLIST_PATH
+        - xcodeproj_path: $BITRISE_PROJECT_PATH
+    - script@1:
+        title: Do anything with Script step
+        inputs:
+        - content: >-
+            bin/env bash
+
+            # fail if any commands fails
+
+            set -e
+
+            # debug log
+
+            set -x
+
+
+            # write your script here
+
+            echo $BITRISE_PROJECT_PATH
+
+            echo $BITRISE_APP_NAME
+
+            echo $XPI_VERSION
+
+            echo $XPI_BUILD
+
+            #IFS=$'\n'
+
+            echo $BITRISE_INFOPLIST_PATH
+
+            buildNumber=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion"
+            $BITRISE_INFOPLIST_PATH)
+
+            echo $buildNumber
+
+            versionNumber=$(/usr/libexec/PlistBuddy -c "Print
+            CFBundleShortVersionString" "${BITRISE_INFOPLIST_PATH}")
+
+            echo $versionNumber
+
+            key="PRODUCT_NAME"
+
+            result=$(xcodebuild -project $BITRISE_PROJECT_PATH
+            -showBuildSettings | grep -w $key)
+
+            productName=$(echo $result | sed "s/^${key} = //")
+
+            echo $productName
+
+            appName=$(/usr/libexec/PlistBuddy -c "Print CFBundleName"
+            "${BITRISE_INFOPLIST_PATH}")
+
+            echo $appName
+    - cache-pull@2: {}
+    - xcode-build-for-simulator@0: {}
+    - appetize-deploy@0:
+        inputs:
+        - app_path: $BITRISE_APP_DIR_PATH_LIST
+        - appetize_token: $BITRISE_APPETIZE_TOKEN
+        - verbose: 'true'
+  WhiteLabelTest:
+    envs:
+    - WHITELABELTEST_PLIST: SwiftNewsCrawler/WhiteLabelTest/Info.plist
+      opts:
+        is_expand: false
+    - WHITELABELTEST_ASSET: SwiftNewsCrawler/WhiteLabelTest/Assets.xcassets
+      opts:
+        is_expand: false
+    - opts:
+        is_expand: false
+      WhiteLabelTest_APPICON: SwiftNewsCrawler/WhiteLabelTest/Assets.xcassets/AppIcon.appiconset
+    - opts:
+        is_expand: false
+      BITRISE_SCHEME: WhiteLabelTest
+    steps:
+    - activate-ssh-key@4:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone@4: {}
+    - cache-pull@2: {}
+    - set-ios-info-plist-unified@1:
+        inputs:
+        - app_icon_asset_catalog: ''
+        - info_plist_file: $WHITELABELTEST_PLIST
+    - xcode-project-info@2:
+        inputs:
+        - info_plist_path: $WHITELABELTEST_PLIST
         - xcodeproj_path: $BITRISE_PROJECT_PATH
     - script@1:
         title: Do anything with Script step
@@ -185,8 +268,6 @@ app:
   - opts:
       is_expand: false
     BITRISE_SCHEME: SwiftNewsCrawler
-  - opts:
-      is_expand: false
-    BITRISE_EXPORT_METHOD: development
+  - BITRISE_EXPORT_METHOD: development
   - BITRISE_INFOPLIST_PATH: SwiftNewsCrawler/SwiftNewsCrawler/Info.plist
   - BITRISE_APPETIZE_TOKEN: tok_kaq602vwkwuv14ajrcrd0zfra8
